name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-darwin:
        runs-on: macOS-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    sudo xcode-select -s /Library/Developer/CommandLineTools
                    mkdir build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    make
                    ./egif_demo
            -   name: Copy File
                run: |
                    cd build
                    mkdir egif
                    mkdir egif/bin/
                    mkdir egif/include
                    mkdir egif/lib
                    mkdir egif/gif
                    cp -rf ../frames egif/
                    cp -f *.gif egif/gif/
                    cp -f egif_demo egif/bin/
                    cp -f libegif.a egif/lib/
                    cp -f ../gif/GifEncoder.h egif/include/
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: egif-darwin-x64
                    path: build/egif

    build-linux:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    mkdir build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    make
                    ./egif_demo
            -   name: Copy File
                run: |
                    cd build
                    mkdir egif
                    mkdir egif/bin/
                    mkdir egif/include
                    mkdir egif/lib
                    mkdir egif/gif
                    cp -rf ../frames egif/
                    cp -f *.gif egif/gif/
                    cp -f egif_demo egif/bin/
                    cp -f libegif.a egif/lib/
                    cp -f ../gif/GifEncoder.h egif/include/
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: egif-linux-x64
                    path: build/egif

    build-windows-x86:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
                    md build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
                    egif_demo.exe
            -   name: Copy File
                shell: bash
                run: |
                    cd build
                    mkdir egif
                    mkdir egif/bin/
                    mkdir egif/include
                    mkdir egif/lib
                    mkdir egif/gif
                    cp -rf ../frames egif/
                    cp -f *.gif egif/gif/
                    cp -f egif_demo.exe egif/bin/
                    cp -f egif.lib egif/lib/
                    cp -f ../gif/GifEncoder.h egif/include/
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: egif-windows-x86
                    path: build/egif

    build-windows-x64:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
                    md build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
                    egif_demo.exe
            -   name: Copy File
                shell: bash
                run: |
                    cd build
                    mkdir egif
                    mkdir egif/bin/
                    mkdir egif/include
                    mkdir egif/lib
                    mkdir egif/gif
                    cp -rf ../frames egif/
                    cp -f *.gif egif/gif/
                    cp -f egif_demo.exe egif/bin/
                    cp -f egif.lib egif/lib/
                    cp -f ../gif/GifEncoder.h egif/include/
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: egif-windows-x64
                    path: build/egif
