name: macos

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    cmake -DCMAKE_BUILD_TYPE=Release -B build .
                    cmake --build build -- all
                    cd build
                    ./egif_demo
            -   name: Copy File
                run: |
                    cd build
                    mkdir egif
                    mkdir egif/bin/
                    mkdir egif/include
                    mkdir egif/lib
                    mkdir egif/gif
                    cp -rf ../frames egif/
                    cp -f *.gif egif/gif/
                    cp -f egif_demo egif/bin/
                    cp -f libegif.a egif/lib/
                    cp -f ../egif/GifEncoder.h egif/include/
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: egif-darwin-x64
                    path: build/egif