name: windows-x86

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-windows-x86:
        runs-on: windows-2019
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
                    cmake -DCMAKE_BUILD_TYPE=Release -GNinja -B build .
                    cmake --build build -- all
                    .\build\egif_demo.exe
            -   name: Copy File
                shell: bash
                run: |
                    cd build
                    mkdir egif
                    mkdir egif/bin/
                    mkdir egif/include
                    mkdir egif/lib
                    mkdir egif/gif
                    cp -rf ../frames egif/
                    cp -f *.gif egif/gif/
                    cp -f egif_demo.exe egif/bin/
                    cp -f egif.lib egif/lib/
                    cp -f ../egif/GifEncoder.h egif/include/
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: egif-windows-x86
                    path: build/egif